version: '3.8'

services:
  app:
    build: .
    ports:
      - "9876:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
